# fly.toml app configuration file generated for division-shapes on 2025-07-18T10:48:10-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'division-shapes'
primary_region = 'ord'

[build]

[deploy]
  strategy = 'immediate'

[env]
  FLASK_ENV = 'production'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[processes]
  app = "python backend.py"

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
  processes = ["app"]
